using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiscordBot.Bot.RealmBot.Game
{
    public class DefaultPointList
    {

        public static Item[] items = [
            // 10 (CB) | 20 (WB) | 20 (OB)
            new Item("Corsair Ring", ["Corsair"], Item.BagType.Cyan, 10, 5, 3),
            new Item("First Mates Hook", ["Hook"], Item.BagType.Orange, 20, 10, 5),
            new Item("Scallywag Slurp", [], Item.BagType.Orange, 80, 40, 20),

            new Item("Bramble Bow", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Cocoon Quiver", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Sapling Buddy", [], Item.BagType.Orange, 80, 40, 20),

            new Item("Poison Fang Dagger", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Spider Shuriken", [], Item.BagType.Cyan, 10, 5, 3), new Item("Shiny Spider Shuriken", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Spiders Eye Ring", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Eggshell Spider", [], Item.BagType.Orange, 80, 40, 20),

            new Item("Staff of the Crystal Serpent", ["Crystal Serpent"], Item.BagType.Cyan, 10, 5, 3), new Item("Shiny Staff of the Crystal Serpent", ["Shiny Crystal Serpent"], Item.BagType.Cyan, 30, 15, 8),
            new Item("Cracked Crystal Skull", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Robe of the Tlatoani", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Crystal Bone Ring", [], Item.BagType.Cyan, 10, 5, 3), new Item("Shiny Crystal Bone Ring", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Baby Basilisk", [], Item.BagType.Orange, 80, 40, 20),

            new Item("Orb of Sweet Demise", ["Sweet Demise"], Item.BagType.Cyan, 10, 5, 3),
            new Item("Honey Scepter", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Bee", [], Item.BagType.Cyan, 20, 10, 5),

            new Item("Wand of the Bulwark", ["Bulwark"], Item.BagType.White, 20, 10, 5),
            new Item("Snake Charmer Pungi", ["Pungi"], Item.BagType.White, 20, 10, 5), new Item("Shiny Snake Charmer Pungi", ["Shiny Pungi"], Item.BagType.White, 60, 30, 15),
            new Item("Snakeskin Shield", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Snakeskin Armor", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Snake Eye Ring", [], Item.BagType.Cyan, 10, 5, 3), new Item("Shiny Snake Eye Ring", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Mini Stheno", [], Item.BagType.Orange, 80, 40, 20),
            new Item("Mini Flying Stheno", [], Item.BagType.Orange, 80, 40, 20),

            new Item("Sprite Wand", [], Item.BagType.Cyan, 10, 5, 3),
            new Item("Staff of Extreme Prejudice", ["ep"], Item.BagType.White, 20, 10, 5), new Item("Shiny Staff of Extreme Prejudice", ["Shiny ep"], Item.BagType.White, 60, 30, 15),
            new Item("Cloak of the Planewalker", ["Planewalker"], Item.BagType.White, 20, 10, 5), new Item("Shiny Cloak of the Planewalker", ["Shiny Planewalker"], Item.BagType.White, 60, 30, 15),
            new Item("Mace of the Celestial Forest", ["Celestial Forest"], Item.BagType.White, 20, 10, 5),
            new Item("Mini Limon", [], Item.BagType.Orange, 80, 40, 20),
            new Item("Sprite Star", [], Item.BagType.Cyan, 20, 10, 5),

            // 15 (CB) | 30 (WB) | 30 (OB)
            new Item("Shiny Kendo Stick", [], Item.BagType.Cyan, 800, 400, 200),

            new Item("Arcane Rapier", ["Rapier"], Item.BagType.White, 30, 15, 8),
            new Item("Amber Encrusted Helmet", [], Item.BagType.Cyan, 15, 8, 4), new Item("Shiny Amber Encrusted Helmet", [], Item.BagType.Cyan, 45, 23, 12),
            new Item("Sandstone Seal", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Resplendent Bow", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Embellished Quiver", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ornate Armor", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Aquamarine Amulet", [], Item.BagType.Orange, 30, 15, 8),

            new Item("Spirit Staff", [], Item.BagType.White, 30, 15, 8),
            new Item("Enchantment Orb", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Enchantment Orb", [], Item.BagType.White, 90, 45, 23),
            new Item("Shield of Flowing Clarity", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Shield of Flowing Clarity", [], Item.BagType.White, 90, 45, 23),
            new Item("Woodland Robe", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Fairy Ring", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Bergenia Bow", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Lifebringing Lotus", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Hollyhock Hide", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Chrysanthemum Corsage", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Fountain Child", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Candy Ring", [], Item.BagType.Cyan, 15, 8, 4), new Item("Shiny Candy Ring", [], Item.BagType.Cyan, 45, 23, 12),
            new Item("Candy Coated Armor", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Candy Coated Armor", [], Item.BagType.White, 90, 45, 23),
            new Item("Pixie Enchanted Sword", ["Pixie"], Item.BagType.Orange, 30, 15, 8),
            new Item("Seal of the Enchanted Forest", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Fairy Plate", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ring of Pure Wishes", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Mini Desire Troll", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Doom Bow", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Doom Bow", [], Item.BagType.White, 90, 45, 23),
            new Item("Wandering Souls Spell", [], Item.BagType.White, 30, 15, 8),
            new Item("Ring of Skeletal Specters", [], Item.BagType.White, 30, 15, 8),
            new Item("Edictum Praetoris", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Toga Picta", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Memento Mori", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Interregnum", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Possessed Staff", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Harlequin Armor", ["Harlequin"], Item.BagType.White, 30, 15, 8), new Item("Shiny Harlequin Armor", ["Shiny Harlequin"], Item.BagType.White, 90, 45, 23),
            new Item("Prism of Dancing Swords", ["Dancing Swords"], Item.BagType.White, 30, 15, 8), new Item("Shiny Prism of Dancing Swords", ["Shiny Dancing Swords"], Item.BagType.White, 90, 45, 23),
            new Item("Puppet Master", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Jester", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Magic Wand", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Lightshow Scepter", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Magicians Robe", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Performers Hat", [], Item.BagType.Orange, 30, 15, 8),

            new Item("Murky Toxin", ["Murky"], Item.BagType.White, 30, 15, 8),
            new Item("Void Blade", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Void Blade", [], Item.BagType.White, 90, 45, 23),
            new Item("Toxin Tooth", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Virulent Venom", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Acidic Armor", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Pernicious Peridot", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Slurp Knight", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Turtle Pet", [], Item.BagType.Cyan, 30, 15, 8),

            new Item("Necronomicon", [], Item.BagType.White, 30, 15, 8),
            new Item("Scholars Seal", [], Item.BagType.White, 30, 15, 8),
            new Item("Ronins Wakizashi", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Corruption Cutter", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Corruption Cutter", [], Item.BagType.White, 90, 45, 23),
            new Item("Deathless Crossbow", ["Deathless"], Item.BagType.Orange, 30, 15, 8),
            new Item("Quiver of Shrieking Specters", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Wraiths Brigandine", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Revenant Ring", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Cultured Bookwyrm", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Enlightened Bookwyrm", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Conducting Wand", [], Item.BagType.White, 30, 15, 8),
            new Item("Scepter of Fulmination", ["Fulmi"], Item.BagType.White, 30, 15, 8),
            new Item("Robe of the Mad Scientist", ["mlab robe"], Item.BagType.White, 30, 15, 8), new Item("Shiny Robe of the Mad Scientist", ["Shiny mlab robe"], Item.BagType.White, 90, 45, 23),
            new Item("Experimental Ring", [], Item.BagType.Cyan, 15, 8, 4), new Item("Shiny Experimental Ring", [], Item.BagType.Cyan, 45, 23, 12),
            new Item("Abominations Wrath", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Grotesque Scepter", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Garment of the Beast", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Horrific Claws", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Robobuddy", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Demon Blade", ["dblade"], Item.BagType.White, 30, 15, 8), new Item("Shiny Demon Blade", ["shiny dblade"], Item.BagType.White, 90, 45, 23),
            new Item("Volcanic Sheath", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Volcanic Sheath", [], Item.BagType.White, 90, 45, 23),
            new Item("Staff of Eruption", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Scorchium Stone", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Molten Mantle", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ring of the Inferno", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Demon Frog", [], Item.BagType.Cyan, 30, 15, 8),
            new Item("Horned Wyrm", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Bone Dagger", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Soulcursed Scythe", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Vampiric Cape", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Hallowed Hide", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ruthvens Rosary", [], Item.BagType.Orange, 30, 15, 8),
            new Item("St Abrahams Wand", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Tome of Purification", ["Puri"], Item.BagType.White, 30, 15, 8), new Item("Shiny Tome of Purification", ["Shiny Puri"], Item.BagType.White, 90, 45, 23),
            new Item("Chasuble of Holy Light", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Ring of Divine Faith", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Vampire Lord", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Amulet of Dispersion", [], Item.BagType.Cyan, 15, 8, 4),
            new Item("Souls Guidance", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Souls Guidance", [], Item.BagType.White, 90, 45, 23),
            new Item("Plague Poison", ["Plague"], Item.BagType.White, 30, 15, 8), new Item("Shiny Plague Poison", ["Shiny Plague"], Item.BagType.White, 90, 45, 23),
            new Item("Resurrected Warriors Armor", ["Resu"], Item.BagType.White, 30, 15, 8), new Item("Shiny Resurrected Warriors Armor", ["Shiny Resu"], Item.BagType.White, 90, 45, 23),
            new Item("Etherite Dagger", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ghastly Drape", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Mantle of Skuld", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Spectral Ring of Horrors", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Werewolf Cub", [], Item.BagType.Orange, 90, 45, 23),

            new Item("Toaster", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Brilliance Bow", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Luxurious Leather", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Regal Ring", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Mister Mango", [], Item.BagType.White, 30, 15, 8),
            new Item("Butter Bow", [], Item.BagType.White, 30, 15, 8),
            new Item("KIDD Force", [], Item.BagType.White, 30, 15, 8),
            new Item("Caduceus of Current Craziness", [], Item.BagType.White, 30, 15, 8),
            new Item("MMace MMurderer", [], Item.BagType.White, 30, 15, 8),
            new Item("Blade of Ages", [], Item.BagType.White, 30, 15, 8),
            new Item("Mirror Cloak", [], Item.BagType.White, 30, 15, 8),
            new Item("Archerang", [], Item.BagType.White, 30, 15, 8),
            new Item("Spelling Spell", [], Item.BagType.White, 30, 15, 8),
            new Item("Tome of Moral Support", [], Item.BagType.White, 30, 15, 8),
            new Item("Challenger Helm", [], Item.BagType.White, 30, 15, 8),
            new Item("Shield of Pogmur", [], Item.BagType.White, 30, 15, 8),
            new Item("Seal of Eternal Life", [], Item.BagType.White, 30, 15, 8),
            new Item("Lightning in a Bottle", [], Item.BagType.White, 30, 15, 8),
            new Item("Epiphany Skull", [], Item.BagType.White, 30, 15, 8),
            new Item("Helium Trap", [], Item.BagType.White, 30, 15, 8),
            new Item("Karma Orb", [], Item.BagType.White, 30, 15, 8),
            new Item("Fools Prism", [], Item.BagType.White, 30, 15, 8),
            new Item("Honey Scepter Supreme", [], Item.BagType.White, 30, 15, 8),
            new Item("Unshuriken", [], Item.BagType.White, 30, 15, 8),
            new Item("NSFWakizashi", [], Item.BagType.White, 30, 15, 8),
            new Item("Lullaby", [], Item.BagType.White, 30, 15, 8),
            new Item("Recursion Mace", [], Item.BagType.White, 30, 15, 8),
            new Item("Paper Machete", [], Item.BagType.White, 30, 15, 8),
            new Item("Cheater Light Armor", [], Item.BagType.White, 30, 15, 8),
            new Item("Cheater Robe", [], Item.BagType.White, 30, 15, 8),
            new Item("Cheater Heavy Armor", [], Item.BagType.White, 30, 15, 8),
            new Item("Omni Impotence Ring", [], Item.BagType.Orange, 30, 15, 8),

            new Item("Alien Core Power", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Suns Judgement", [], Item.BagType.White, 30, 15, 8),
            new Item("Fire Blade", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Fire Blade", [], Item.BagType.White, 90, 45, 23),
            new Item("Comet of Calamity", [], Item.BagType.White, 30, 15, 8),

            new Item("Alien Core Dark Matter", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Moonbeam Blade", [], Item.BagType.White, 30, 15, 8),
            new Item("Dueling Daggers", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Dueling Daggers", [], Item.BagType.White, 90, 45, 23),
            new Item("Snowblind Wand", [], Item.BagType.White, 30, 15, 8),

            new Item("Alien Core Warp", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Warlord Wand", [], Item.BagType.White, 30, 15, 8),
            new Item("Gaseous Glaive", [], Item.BagType.White, 30, 15, 8),
            new Item("Blazon Bow", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Blazon Bow", [], Item.BagType.White, 90, 45, 23),

            new Item("Alien Core Corrosion", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Foramite Staff", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Foramite Staff", [], Item.BagType.White, 90, 45, 23),
            new Item("Acidic Slasher", [], Item.BagType.White, 30, 15, 8),
            new Item("Corrosion Cutter", [], Item.BagType.White, 30, 15, 8),

            new Item("Ancient Stone Sword", ["Ass"], Item.BagType.White, 30, 15, 8), new Item("Shiny Ancient Stone Sword", ["Shiny Ass", "Swamp Ass", "Eggplant"], Item.BagType.White, 90, 45, 23),
            new Item("Spiteful Scutum", ["Scutum"], Item.BagType.White, 30, 15, 8),
            new Item("Theurgy Wand", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ceremonial Merlot", ["Merlot"], Item.BagType.Orange, 30, 15, 8),
            new Item("Anointed Robe", ["Anointed"], Item.BagType.Orange, 30, 15, 8),
            new Item("Ring of Pagan Favor", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Cloak of the Mad God", [], Item.BagType.White, 30, 15, 8), new Item("Shiny Cloak of the Mad God", [], Item.BagType.White, 90, 45, 23),
            new Item("Chicken Leg of Doom", [], Item.BagType.White, 30, 15, 8),
            new Item("Anatis Staff", [], Item.BagType.White, 30, 15, 8),
            new Item("Apocalypse Feather", [], Item.BagType.White, 30, 15, 8),

            new Item("Miss Shamrock", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Leperchauns Walking Hat", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Green Hat Bunny", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Mini Pot of Gold", [], Item.BagType.Orange, 90, 45, 23),
            new Item("Painbow", [], Item.BagType.White, 30, 15, 8),
            new Item("Prismatic Slasher", [], Item.BagType.White, 30, 15, 8),
            new Item("Rainbow Rod", [], Item.BagType.White, 30, 15, 8),
            new Item("Staff of the Saint", [], Item.BagType.White, 30, 15, 8),
            new Item("Sword of the Rainbows End", [], Item.BagType.White, 30, 15, 8),
            new Item("Clover Bow", [], Item.BagType.White, 30, 15, 8),
            new Item("Katana of Good Fortune", [], Item.BagType.White, 30, 15, 8),
            new Item("Clover Star", [], Item.BagType.White, 30, 15, 8),

            new Item("The Phylactery", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Soul of the Bearer", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Soulless Robe", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Ring of the Covetous Heart", [], Item.BagType.Orange, 30, 15, 8),

            new Item("Kiritsukeru", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Watarimono", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Reinforced Root Armor", [], Item.BagType.Orange, 30, 15, 8),
            new Item("Travelers Trinket", [], Item.BagType.Orange, 30, 15, 8),

            // 25 (CB) | 45 (WB) | 45 (OB)
            new Item("Spirit Dagger", [], Item.BagType.White, 45, 23, 12),
            new Item("Ghostly Prism", [], Item.BagType.White, 45, 23, 12),
            new Item("Spectral Cloth Armor", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Captains Ring", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Spirit Pet", [], Item.BagType.Cyan, 50, 25, 13),
            new Item("Quartermaster Scabbard", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Quartermaster Scabbard", [], Item.BagType.White, 135, 68, 34),
            new Item("Lil Davy", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Staff of Esben", [], Item.BagType.White, 45, 23, 12),
            new Item("Skullish Remains of Esben", [], Item.BagType.White, 45, 23, 12),
            new Item("Esbens Shaman Attire", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Esbens Shaman Attire", [], Item.BagType.White, 135, 68, 34),
            new Item("Esbens Wedding Ring", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Esbens Wedding Ring", [], Item.BagType.White, 135, 68, 34),
            new Item("Dalvars Battle Axe", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Sunken Buckler", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Chainmail Body Armor", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Gjallarhorn", [], Item.BagType.Orange, 45, 23, 12),

            new Item("Tideturner Trident", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Slurpian Sea Scroll", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Oceanic Apparel", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Imperial Keepsake", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Coral Bow", ["cbow"], Item.BagType.White, 45, 23, 12), new Item("Shiny Coral Bow", ["shiny cbow"], Item.BagType.White, 135, 68, 34),
            new Item("Coral Venom Trap", ["ctrap"], Item.BagType.White, 45, 23, 12),
            new Item("Coral Silk Armor", [], Item.BagType.Cyan, 25, 13, 7), new Item("Shiny Coral Silk Armor", [], Item.BagType.Cyan, 75, 38, 19),
            new Item("Coral Ring", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Sea Slurp", [], Item.BagType.Cyan, 50, 25, 13),

            new Item("Doku No Ken", ["doku"], Item.BagType.White, 45, 23, 12), new Item("Shiny Doku No Ken", ["shiny doku"], Item.BagType.White, 135, 68, 34),
            new Item("Mace of the Depths", [], Item.BagType.White, 45, 23, 12),

            new Item("Leaf Bow", ["lbow"], Item.BagType.White, 45, 23, 12), new Item("Shiny Leaf Bow", ["shiny lbow"], Item.BagType.White, 135, 68, 34),
            new Item("Wakizashi of Eastern Winds", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Wakizashi of Eastern Winds", [], Item.BagType.White, 135, 68, 34),
            new Item("Labyrinth Dwellers Sheath", [], Item.BagType.White, 45, 23, 12),
            new Item("Blessed Blade", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Pirate Kings Cutlass", ["cutlass"], Item.BagType.White, 45, 23, 12), new Item("Shiny Pirate Kings Cutlass", ["shiny cutlass"], Item.BagType.White, 135, 68, 34),
            new Item("Wavecrest Concertina", ["Concertina"], Item.BagType.White, 45, 23, 12), new Item("Shiny Wavecrest Concertina", ["Shiny Concertina"], Item.BagType.White, 135, 68, 34),
            new Item("Swashbucklers Sickle", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Tricorne of the High Seas", ["Tricorne"], Item.BagType.Orange, 45, 23, 12),
            new Item("Naval Uniform", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Calamity Crab", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Thousand Shot", [], Item.BagType.White, 45, 23, 12),
            new Item("Prism of Dire Instability", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Prism of Dire Instability", [], Item.BagType.White, 135, 68, 34),

            new Item("Bottled Medusozoan", [], Item.BagType.White, 45, 23, 12),
            new Item("Cnidaria Rod", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Cnidaria Rod", [], Item.BagType.White, 135, 68, 34),
            new Item("Jellyhead trickster", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Brambletooth Tachi", [], Item.BagType.White, 45, 23, 12),
            new Item("Bogwood Crook", [], Item.BagType.White, 45, 23, 12),
            new Item("Warped Mantle", [], Item.BagType.White, 45, 23, 12),
            new Item("Thistleleaf Necklace", [], Item.BagType.White, 45, 23, 12),
            new Item("Sulfuric Stone", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Swamped Panda", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Recurring Terror Spell", ["para spell"], Item.BagType.White, 45, 23, 12), new Item("Shiny Recurring Terror Spell", ["shiny para spell"], Item.BagType.White, 135, 68, 34),
            new Item("Scepter of Devastation", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Scepter of Devastation", [], Item.BagType.White, 135, 68, 34),
            new Item("Tome of Pain", [], Item.BagType.White, 45, 23, 12),
            new Item("Symbiotic Ripper", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Parasitic Concoction", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Rags of the Host", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Hivemind Circlet", [], Item.BagType.Orange, 45, 23, 12),

            new Item("Wand of the Fallen", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Wand of the Fallen", [], Item.BagType.White, 135, 68, 34),
            new Item("Orb of Aether", [], Item.BagType.White, 45, 23, 12),
            new Item("Jade Storm", [], Item.BagType.White, 45, 23, 12),
            new Item("Kaiken", [], Item.BagType.White, 45, 23, 12),
            new Item("Kazekiri", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Ryus Blade", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Kamishimo", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Akumas Tear", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Possessed Lantern", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Celestial Blade", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Celestial Blade", [], Item.BagType.White, 135, 68, 34),
            new Item("Leaf Dragon Hide Armor", [], Item.BagType.White, 45, 23, 12),
            new Item("Water Dragon Silk Robe", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Water Dragon Silk Robe", [], Item.BagType.White, 135, 68, 34),
            new Item("Fire Dragon Battle Armor", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Fire Dragon Battle Armor", [], Item.BagType.White, 135, 68, 34),
            new Item("Midnight Star", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Midnight Star", [], Item.BagType.White, 135, 68, 34),
            new Item("Hailstorm", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Thundering Chorus", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Wind Dancer Robe", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Augur of the Tempest", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Earthen Ward", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Stonemould Mace", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Rocky Robe", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Steadfast Glyph", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Saif of the Deep", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Loch Sheath", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Barrier Reef", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Alexanders Band", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Indomptable", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Helm of Draconic Dominance", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Zaarvoxs Heart", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Amulet of Drakefyre", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Wicked Dragon Wizard", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Mini Nikao", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Ring of the Pyramid", ["pyra"], Item.BagType.White, 45, 23, 12),
            new Item("Tome of Holy Protection", ["prot"], Item.BagType.White, 45, 23, 12), new Item("Shiny Tome of Holy Protection", ["Shiny prot"], Item.BagType.White, 135, 68, 34),
            new Item("Ring of the Sphinx", ["sphinx"], Item.BagType.White, 45, 23, 12),
            new Item("Pharaohs Requiem", [], Item.BagType.White, 45, 23, 12),
            new Item("Ring of the Nile", ["nile"], Item.BagType.White, 45, 23, 12),
            new Item("Wand of Geb", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Book of Geb", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Shendyt of Geb", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Gebs Ring of Wisdom", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Mini nut archer", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Mini geb", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Bess artifact", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Nuts artifact", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Gebs artifact", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Tomb Snake", [], Item.BagType.Cyan, 50, 25, 13),

            new Item("Cloak of Cubic Enigma", [], Item.BagType.White, 45, 23, 12),
            new Item("Seal of Cubic Conundra", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Seal of Cubic Conundra", [], Item.BagType.White, 135, 68, 34),
            new Item("Shadow Serpent Sidearm", [], Item.BagType.White, 45, 23, 12),
            new Item("Squaroid Staff", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Cubic Frame", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Polygonal Garbs", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Cuband", [], Item.BagType.Orange, 45, 23, 12),

            new Item("Skull of Endless Torment", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Skull of Endless Torment", [], Item.BagType.White, 135, 68, 34),
            new Item("Wakizashi of Crossing Fires", [], Item.BagType.White, 45, 23, 12),
            new Item("Fiery Katana", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Pyro Sheath", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Flame Guard", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Firelight Necklace", [], Item.BagType.Orange, 45, 23, 12),

            new Item("Good mask spirit", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Evil mask spirit", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Tlatoanis Shroud", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Tezcacoatls Tail", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Tezcacoatls Tail", [], Item.BagType.White, 135, 68, 34),
            new Item("Sealed Crystal Skull", [], Item.BagType.White, 45, 23, 12),
            new Item("Penetrating Blast Spell", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Penetrating Blast Spell", [], Item.BagType.White, 135, 68, 34),
            new Item("Reikoku", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Daybreak Chakram", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Hirejou Tenne", ["Tenne"], Item.BagType.Orange, 45, 23, 12),
            new Item("Heavenly Magatama", [], Item.BagType.Orange, 45, 23, 12),

            new Item("BOW", [], Item.BagType.White, 45, 23, 12),
            new Item("STAFF", [], Item.BagType.White, 45, 23, 12), new Item("Shiny STAFF", [], Item.BagType.White, 135, 68, 34),
            new Item("QUIVER", [], Item.BagType.White, 45, 23, 12),
            new Item("EYE", [], Item.BagType.White, 45, 23, 12), new Item("Shiny EYE", [], Item.BagType.White, 135, 68, 34),
            new Item("CLAW", [], Item.BagType.Orange, 45, 23, 12),
            new Item("BOOM", [], Item.BagType.Orange, 45, 23, 12),
            new Item("ARMOR", [], Item.BagType.Orange, 45, 23, 12),
            new Item("CONTROLLER", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Blizzard", [], Item.BagType.Orange, 135, 68, 34),

            new Item("The Right Hook", [], Item.BagType.White, 45, 23, 12), new Item("Shiny The Right Hook", [], Item.BagType.White, 135, 68, 34),
            new Item("Tipsy Topper", [], Item.BagType.White, 45, 23, 12),
            new Item("Double Vision Darts", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Double Vision Darts", [], Item.BagType.White, 135, 68, 34),
            new Item("Cask Corslet", [], Item.BagType.White, 45, 23, 12),
            new Item("Brewers Bangle", [], Item.BagType.White, 45, 23, 12),

            new Item("Tome of Holy Furor", [], Item.BagType.White, 45, 23, 12),
            new Item("Oryxs Greatsword", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Champions Bastion", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Mercys Bane", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Bloodstone Ring", [], Item.BagType.Orange, 45, 23, 12),

            new Item("Arctic Bow", [], Item.BagType.White, 45, 23, 12),
            new Item("Freezing Quiver", [], Item.BagType.White, 300, 150, 75),
            new Item("Frimarra", [], Item.BagType.White, 45, 23, 12),
            new Item("Enchanted Ice Shard", [], Item.BagType.White, 45, 23, 12),
            new Item("Ring of the Northern Light", [], Item.BagType.White, 45, 23, 12),

            new Item("Sunshine Shiv", [], Item.BagType.White, 45, 23, 12),
            new Item("Robobow", [], Item.BagType.White, 45, 23, 12),
            new Item("Spicy Wand of Spice", [], Item.BagType.White, 45, 23, 12),
            new Item("Doctor Swordsworth", [], Item.BagType.White, 45, 23, 12),
            new Item("Arbiters Wrath", [], Item.BagType.White, 45, 23, 12),
            new Item("KoalaPOW", [], Item.BagType.White, 45, 23, 12),

            new Item("Bashing bride", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Eligible Bachelor", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Heartseeker huntress", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Little prince", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Little fox", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Sprout Slime", [], Item.BagType.Orange, 135, 68, 34),
            new Item("Perennial Cranium", [], Item.BagType.White, 45, 23, 12),
            new Item("Hanagasaku", [], Item.BagType.White, 45, 23, 12),

            new Item("Bunny Ear Tachi", [], Item.BagType.White, 45, 23, 12),
            new Item("Caramel Spellblade", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Shard Launcher", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Egg Basher", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Chocolate Ovipositor", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Hatchling Blades", [], Item.BagType.Cyan, 25, 13, 7),

            new Item("Precisely Calibrated Stringstick", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Lethargic Sentience", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Toy Knife", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Barely Attuned Magic Thingy", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Unstable Anomaly", [], Item.BagType.Cyan, 25, 13, 7),
            new Item("Random Spell Extraction Device", [], Item.BagType.White, 45, 23, 12),
            new Item("Krathana", [], Item.BagType.White, 45, 23, 12),
            new Item("Silexs Hammer", [], Item.BagType.White, 45, 23, 12),

            new Item("Obsidian Macuahuitl", [], Item.BagType.White, 45, 23, 12),
            new Item("Pirates Sidearms", [], Item.BagType.White, 45, 23, 12),
            new Item("Ritual Khopesh", [], Item.BagType.White, 45, 23, 12),
            new Item("Gilded Chain Scythe", [], Item.BagType.White, 45, 23, 12),
            new Item("Frangible Longbow", [], Item.BagType.White, 45, 23, 12),
            new Item("Royal Sekhem", [], Item.BagType.White, 45, 23, 12),
            new Item("Heavy Syndicate Attire", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Heavy Syndicate Attire", [], Item.BagType.White, 135, 68, 34),
            new Item("Mystic Syndicate Attire", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Mystic Syndicate Attire", [], Item.BagType.White, 135, 68, 34),
            new Item("Light Syndicate Attire", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Light Syndicate Attire", [], Item.BagType.White, 135, 68, 34),
            new Item("Rusted Barrel", [], Item.BagType.White, 45, 23, 12),
            new Item("Storm Caller", [], Item.BagType.White, 45, 23, 12),
            new Item("Huntsmans Volley", [], Item.BagType.White, 45, 23, 12),
            new Item("Fractured Hannya", [], Item.BagType.White, 45, 23, 12),
            new Item("Sunken Fire Opal Ring", [], Item.BagType.White, 45, 23, 12),
            new Item("Faded Heart Scarab", [], Item.BagType.White, 45, 23, 12),
            new Item("Beach Party Necromancer", [], Item.BagType.Orange, 135, 68, 34),

            new Item("Evergreen Dagger", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Evergreen Dagger", [], Item.BagType.White, 135, 68, 34),
            new Item("Garland Bow", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Garland Bow", [], Item.BagType.White, 135, 68, 34),
            new Item("Sleigh Bell Staff", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Sleigh Bell Staff", [], Item.BagType.White, 135, 68, 34),
            new Item("Brass Chamberstick", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Brass Chamberstick", [], Item.BagType.White, 135, 68, 34),
            new Item("Cheerful Chipper", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Cheerful Chipper", [], Item.BagType.White, 135, 68, 34),
            new Item("Candy Katana", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Candy Katana", [], Item.BagType.White, 135, 68, 34),

            new Item("Crystal Sword", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Crystal Sword", [], Item.BagType.White, 135, 68, 34),
            new Item("Crystal Wand", [], Item.BagType.White, 45, 23, 12),
            new Item("Crystal Mace", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Crystal Mace", [], Item.BagType.White, 135, 68, 34),
            new Item("Mini Crystal Steed", [], Item.BagType.Golden, 135, 68, 34),

            new Item("Deadly Keg", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Deadly Keg", [], Item.BagType.White, 135, 68, 34),
            new Item("Mighty Stein", [], Item.BagType.White, 45, 23, 12),
            new Item("Greaterhosen", [], Item.BagType.White, 45, 23, 12), new Item("Shiny Greaterhosen", [], Item.BagType.White, 135, 68, 34),

            new Item("Helm of the Swift Bunny", [], Item.BagType.White, 45, 23, 12),

            new Item("Mimicry Trap", [], Item.BagType.White, 45, 23, 12),
            new Item("Prismimic", [], Item.BagType.White, 45, 23, 12),

            new Item("Space Smuggler Rogue", [], Item.BagType.Golden, 45, 23, 12),
            new Item("Locked Reactor", [], Item.BagType.Orange, 45, 23, 12),
            new Item("Fitted Protective Matrix", [], Item.BagType.White, 45, 23, 12),
            new Item("Magic Protective Matrix", [], Item.BagType.White, 45, 23, 12),
            new Item("Heavy Protective Matrix", [], Item.BagType.White, 45, 23, 12),

            new Item("Heart of Gold Prism", [], Item.BagType.White, 45, 23, 12),
            new Item("Gem of Tenderness", [], Item.BagType.White, 45, 23, 12),
            new Item("Gem of Adoration", [], Item.BagType.White, 45, 23, 12),

            // 35 (CB) | 70 (WB) | 55 (OB) | 55 (EB)
            new Item("Sages Wakibiki", [], Item.BagType.White, 70, 35, 18),
            new Item("Ethereal Happi", [], Item.BagType.White, 70, 35, 18),
            new Item("Flowering Kimono", [], Item.BagType.White, 70, 35, 18),
            new Item("Rain Maker", [], Item.BagType.White, 70, 35, 18),
            new Item("Taiko Drums", [], Item.BagType.White, 70, 35, 18),
            new Item("Elegant Parasol", [], Item.BagType.White, 70, 35, 18),
            new Item("Festival Enjoyer Kensei", [], Item.BagType.Orange, 180, 90, 45),
            new Item("Festival Enjoyer Bard", [], Item.BagType.Orange, 180, 90, 45),
            new Item("Makakoyumi", [], Item.BagType.White, 70, 35, 18),
            new Item("Tezutsu Hanabi", [], Item.BagType.White, 70, 35, 18),
            new Item("Kagenohikari", [], Item.BagType.White, 70, 35, 18),
            new Item("Concentrated Soul Fire", [], Item.BagType.White, 70, 35, 18),
            new Item("Master Fishing Rod", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Master Fishing Rod", [], Item.BagType.White, 210, 105, 53),

            new Item("Nest Engraving Chest", "Engraving Chest", ["Nest Engraving"], Item.BagType.Orange, 55, 28, 14),
            new Item("Queens Stinger", [], Item.BagType.White, 70, 35, 18), new Item("Queens Stinger Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Green Beehemoth Quiver", [], Item.BagType.White, 300, 150, 75),
            new Item("Hivemaster Helm", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Hivemaster Helm", [], Item.BagType.White, 210, 105, 53), new Item("Hivemaster Helm Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Hivemind Mace", [], Item.BagType.White, 70, 35, 18), new Item("Hivemind Mace Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Beekeepers Flamethrower", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Beekeepers Flamethrower", [], Item.BagType.White, 210, 105, 53), new Item("Beekeepers Flamethrower Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Nectar Crossfire", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Honeytomb Snare", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Apiary Armor", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Honey Circlet", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Blue Beehemoth Armor", [], Item.BagType.Cyan, 35, 18, 9),
            new Item("Green Beehemoth Armor", [], Item.BagType.Cyan, 35, 18, 9),
            new Item("Red Beehemoth Armor", [], Item.BagType.Cyan, 35, 18, 9),
            new Item("Yellow Beehemoth Armor", [], Item.BagType.Cyan, 35, 18, 9),
            new Item("Killer Bee Queen", [], Item.BagType.Orange, 180, 90, 45),

            new Item("Mini Malus Sorcerer", [], Item.BagType.Orange, 180, 90, 45),
            new Item("Staff of Unholy Sacrifice", [], Item.BagType.White, 70, 35, 18), new Item("Staff of Unholy Sacrifice Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Skull of Corrupted Souls", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Skull of Corrupted Souls", [], Item.BagType.White, 210, 105, 53), new Item("Skull of Corrupted Souls Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Ritual Robe", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Ritual Robe", [], Item.BagType.White, 210, 105, 53), new Item("Ritual Robe Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Bloodshed Ring", [], Item.BagType.White, 70, 35, 18), new Item("Bloodshed Ring Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Burial Blades", [], Item.BagType.White, 70, 35, 18), new Item("Burial Blades Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),

            new Item("Ring of Decades", ["Deca"], Item.BagType.Red, 70, 35, 18), new Item("Shiny Ring of Decades", ["Shiny Deca"], Item.BagType.Red, 210, 105, 53),
            new Item("Fungal Breastplate", [], Item.BagType.White, 70, 35, 18),
            new Item("Crystal Shield", ["cshield"], Item.BagType.White, 70, 35, 18), new Item("Shiny Crystal Shield", ["shiny cshield"], Item.BagType.White, 210, 105, 53), new Item("Crystal Shield Blueprint", "Exalted Blueprint", ["cshield blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Sporous Spray Spell", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Sporous Spray Spell", [], Item.BagType.White, 210, 105, 53), new Item("Sporous Spray Spell Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Tome of the Mushroom Tribes", ["Mushroom tome"], Item.BagType.White, 70, 35, 18), new Item("Shiny Tome of the Mushroom Tribes", ["Shiny Mushroom tome"], Item.BagType.White, 210, 105, 53), new Item("Tome of the Mushroom Tribes Blueprint", "Exalted Blueprint", ["Mushroom tome blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Cave Dweller Trap", [], Item.BagType.White, 70, 35, 18), new Item("Cave Dweller Trap Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Crystallized Worm Spellblade", [], Item.BagType.White, 70, 35, 18), new Item("Crystallized Worm Spellblade Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Quartz Cutter", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Crystalline Kunai", ["Kunai"], Item.BagType.Orange, 55, 28, 14),
            new Item("Luminous Armor", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Radiant Heart", [], Item.BagType.Orange, 55, 28, 14),

            new Item("Cloak of Refraction", [], Item.BagType.White, 70, 35, 18), new Item("Cloak of Refraction Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Crystallised Mist", [], Item.BagType.White, 70, 35, 18), new Item("Crystallised Mist Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Echoes Prism", [], Item.BagType.White, 70, 35, 18), new Item("Echoes Prism Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Fractured Gemstone Wakizashi", [], Item.BagType.White, 70, 35, 18), new Item("Fractured Gemstone Wakizashi Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Star of Enlightenment", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Star of Enlightenment", [], Item.BagType.White, 210, 105, 53), new Item("Star of Enlightenment Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Fractal Blades", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Fractal Blades", [], Item.BagType.White, 210, 105, 53), new Item("Fractal Blades Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Irradiance Sheath", [], Item.BagType.White, 70, 35, 18), new Item("Irradiance Sheath Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Crystal Cobra", [], Item.BagType.Orange, 180, 90, 45),

            new Item("Tools of the Tarnished", [], Item.BagType.White, 70, 35, 18),
            new Item("Wretched Rags", [], Item.BagType.White, 70, 35, 18),
            new Item("Sinister Syringes", [], Item.BagType.White, 70, 35, 18),
            new Item("Cackling Straitjacket", [], Item.BagType.White, 70, 35, 18),
            new Item("Command Cornea", [], Item.BagType.White, 70, 35, 18),
            new Item("Ocular Entrapment", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Ocular Entrapment", [], Item.BagType.White, 210, 105, 53),
            new Item("Overwhelming Axehead", [], Item.BagType.White, 70, 35, 18),
            new Item("Motivational Megaphone", [], Item.BagType.White, 70, 35, 18),
            new Item("Damnation", [], Item.BagType.White, 70, 35, 18),
            new Item("Vial of Soul Extract", [], Item.BagType.White, 70, 35, 18),
            new Item("Penitent Frog", [], Item.BagType.Orange, 180, 90, 45),

            new Item("Kogbold Engraving Chest", "Engraving Chest", ["Kobold Engraving"], Item.BagType.Orange, 55, 28, 14),
            new Item("Overclocking Amulet", [], Item.BagType.White, 70, 35, 18), new Item("Overclocking Amulet Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Steam Pipe", [], Item.BagType.White, 70, 35, 18), new Item("Steam Pipe Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Kogbold Cower Shield", [], Item.BagType.White, 70, 35, 18), new Item("Kogbold Cower Shield Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Scepter of Rust", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Scepter of Rust", [], Item.BagType.White, 210, 105, 53), new Item("Scepter of Rust Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Brain Cube", [], Item.BagType.White, 70, 35, 18), new Item("Brain Cube Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Chain Dagger", [], Item.BagType.White, 70, 35, 18), new Item("Chain Dagger Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Laser Pointer", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Laser Pointer", [], Item.BagType.White, 210, 105, 53), new Item("Laser Pointer Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Kogbold Enhancement Core", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Kogbold Enhancement Core", [], Item.BagType.White, 210, 105, 53),
            new Item("Kogbold Maid", [], Item.BagType.Orange, 180, 90, 45),

            new Item("Sword of the Colossus", ["Colo"], Item.BagType.White, 70, 35, 18), new Item("Shiny Sword of the Colossus", ["Shiny Colo"], Item.BagType.White, 210, 105, 53), new Item("Sword of the Colossus Blueprint", "Exalted Blueprint", ["Colo blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Marble Seal", ["mseal"], Item.BagType.White, 70, 35, 18), new Item("Marble Seal Blueprint", "Exalted Blueprint", ["mseal blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Breastplate of New Life", ["breastplate"], Item.BagType.White, 70, 35, 18), new Item("Breastplate of New Life Blueprint", "Exalted Blueprint", ["breastplate blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Magical Lodestone", ["potato"], Item.BagType.White, 70, 35, 18), new Item("Magical Lodestone Blueprint", "Exalted Blueprint", ["potato blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Carved Golem Remains", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Brain of the Golem", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Golem Garments", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Rusty Cuffs", [], Item.BagType.Orange, 55, 28, 14),

            new Item("Bow of the Void", ["Void Bow"], Item.BagType.White, 70, 35, 18), new Item("Shiny Bow of the Void", ["Shiny Void Bow"], Item.BagType.White, 210, 105, 53), new Item("Bow of the Void Blueprint", "Exalted Blueprint", ["Void Bow Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Quiver of the Shadows", ["Void Quiver"], Item.BagType.White, 70, 35, 18), new Item("Shiny Quiver of the Shadows", ["Shiny Void Quiver"], Item.BagType.White, 210, 105, 53), new Item("Quiver of the Shadows Blueprint", "Exalted Blueprint", ["Void Quiver Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Armor of Nil", [], Item.BagType.White, 70, 35, 18), new Item("Armor of Nil Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Sourcestone", [], Item.BagType.White, 70, 35, 18), new Item("Sourcestone Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Omnipotence Ring", ["Omni"], Item.BagType.White, 70, 35, 18), new Item("Omnipotence Ring Blueprint", "Exalted Blueprint", ["Omni blueprint"], Item.BagType.Blue, 55, 28, 14),

            new Item("The Forgotten Ring", [], Item.BagType.Red, 70, 35, 18),
            new Item("Royal Guards Cuirass", [], Item.BagType.White, 70, 35, 18), new Item("Royal Guards Cuirass Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Valor", [], Item.BagType.White, 70, 35, 18), new Item("Valor Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Vanguards Visage", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Vanguards Visage", [], Item.BagType.White, 210, 105, 53), new Item("Vanguards Visage Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Sentinels Sidearm", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Sentinels Sidearm", [], Item.BagType.White, 210, 105, 53), new Item("Sentinels Sidearm Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Bracer of the Guardian", ["Bracer"], Item.BagType.White, 70, 35, 18), new Item("Bracer of the Guardian Blueprint", "Exalted Blueprint", ["Bracer Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Vest of Abandoned Shadows", [], Item.BagType.White, 70, 35, 18), new Item("Vest of Abandoned Shadows Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Dusky Catalyst", [], Item.BagType.White, 70, 35, 18), new Item("Dusky Catalyst Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Primal Arcana", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Primal Arcana", [], Item.BagType.White, 210, 105, 53), new Item("Primal Arcana Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Polarity Poison", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Polarity Poison", [], Item.BagType.White, 210, 105, 53), new Item("Polarity Poison Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("The Twilight Gemstone", ["Gemstone"], Item.BagType.White, 70, 35, 18), new Item("Shiny The Twilight Gemstone", ["Shiny Gemstone"], Item.BagType.White, 210, 105, 53), new Item("The Twilight Gemstone Blueprint", "Exalted Blueprint", ["Gemstone blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Mantle of the Monarchy", [], Item.BagType.White, 70, 35, 18), new Item("Mantle of the Monarchy Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Warmonger", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Warmonger", [], Item.BagType.White, 210, 105, 53), new Item("Warmonger Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Peacekeeper", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Peacekeeper", [], Item.BagType.White, 210, 105, 53), new Item("Peacekeeper Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Noble Mandolin", [], Item.BagType.White, 70, 35, 18), new Item("Noble Mandolin Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("The Forgotten Crown", ["Crown"], Item.BagType.White, 140, 70, 35), new Item("The Forgotten Crown Blueprint", "Exalted Blueprint", ["Crown blueprint"], Item.BagType.Blue, 140, 70, 35),
            new Item("Chrysalis of Eternity", ["Lean crown", "Lean"], Item.BagType.White, 70, 35, 18),
            new Item("Corruption Tether", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Ancient Eminence", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Twilight Shroud", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Defiled Equilibrium", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Archangels Judgement", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Daevite Progenitor", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Seraphims Guard", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Flames of Genesis", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Fallen Ones Blade", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Abyssal Insignia", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Vortex Plating", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Eye of the Void", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Sentinel watchdog", [], Item.BagType.Orange, 180, 90, 45),
            new Item("Shadow stormbird", [], Item.BagType.Orange, 180, 90, 45),
            new Item("Royal void cat", [], Item.BagType.Orange, 180, 90, 45),

            new Item("Superior", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Superior", [], Item.BagType.White, 210, 105, 53), new Item("Superior Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Genesis Spell", [], Item.BagType.White, 70, 35, 18), new Item("Genesis Spell Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Diplomatic Robe", ["Diplo"], Item.BagType.White, 70, 35, 18), new Item("Shiny Diplomatic Robe", ["Shiny Diplo"], Item.BagType.White, 210, 105, 53), new Item("Diplomatic Robe Blueprint", "Exalted Blueprint", ["Diplo blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Chancellors Cranium", [], Item.BagType.White, 70, 35, 18), new Item("Chancellors Cranium Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Avarice", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Avarice", [], Item.BagType.White, 210, 105, 53), new Item("Avarice Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Gamblers Fate", ["Coin"], Item.BagType.White, 70, 35, 18), new Item("Gamblers Fate Blueprint", "Exalted Blueprint", ["Coin Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Turncoat Cape", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Turncoat Cape", [], Item.BagType.White, 210, 105, 53), new Item("Turncoat Cape Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Collectors Monocle", ["Monocole"], Item.BagType.White, 70, 35, 18), new Item("Collectors Monocle Blueprint", "Exalted Blueprint", ["Monocle Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Lumiaire", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Lumiaire", [], Item.BagType.White, 210, 105, 53), new Item("Lumiaire Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Chaotic Scripture", ["Scripture"], Item.BagType.White, 70, 35, 18), new Item("Chaotic Scripture Blueprint", "Exalted Blueprint", ["Scripture blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Vesture of Duality", ["Vesture"], Item.BagType.White, 70, 35, 18), new Item("Shiny Vesture of Duality", ["Shiny Vesture"], Item.BagType.White, 210, 105, 53), new Item("Vesture of Duality Blueprint", "Exalted Blueprint", ["Vesture Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Divine Coronation", ["Coronation"], Item.BagType.White, 70, 35, 18), new Item("Divine Coronation Blueprint", "Exalted Blueprint", ["Coronation Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Enforcer", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Enforcer", [], Item.BagType.White, 210, 105, 53), new Item("Enforcer Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Ballistic Star", [], Item.BagType.White, 70, 35, 18), new Item("Ballistic Star Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Centaurs Shielding", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Centaurs Shielding", [], Item.BagType.White, 210, 105, 53), new Item("Centaurs Shielding Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Battalion Banner", ["Banner"], Item.BagType.White, 70, 35, 18), new Item("Battalion Banner Blueprint", "Exalted Blueprint", ["Banner Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Divinity", [], Item.BagType.White, 70, 35, 18), new Item("Shiny Divinity", [], Item.BagType.White, 210, 105, 53), new Item("Divinity Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 55, 28, 14),
            new Item("Oryxs Escutcheon", ["Escutcheon"], Item.BagType.White, 70, 35, 18), new Item("Oryxs Escutcheon Blueprint", "Exalted Blueprint", ["Escutcheon blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Gladiator Guard", ["Glad Guard"], Item.BagType.White, 70, 35, 18), new Item("Shiny Gladiator Guard", ["Shiny Glad Guard"], Item.BagType.White, 210, 105, 53), new Item("Gladiator Guard Blueprint", "Exalted Blueprint", ["Glad guard blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Exalted Gods Horn", ["Horn"], Item.BagType.White, 70, 35, 18), new Item("Exalted Gods Horn Blueprint", "Exalted Blueprint", ["Horn Blueprint"], Item.BagType.Blue, 55, 28, 14),
            new Item("Harmonious Harp", ["Harp"], Item.BagType.Orange, 55, 28, 14),
            new Item("Angels Fanfare", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Wings of Sanctity", [], Item.BagType.Orange, 55, 28, 14),
            new Item("Heavenly Halo", [], Item.BagType.Orange, 55, 28, 14),

            // Biome Whites + Event Whites
            new Item("Adventurers Scarf", [], Item.BagType.White, 300, 150, 75),
            new Item("Torrential Staff", [], Item.BagType.White, 300, 150, 75),
            new Item("Celestial Recurve", [], Item.BagType.White, 300, 150, 75),
            new Item("Mace of the Pumpkin Effigy", [], Item.BagType.White, 300, 150, 75),
            new Item("Pirates Artillery", [], Item.BagType.White, 300, 150, 75),
            new Item("Skull of Restless Souls", [], Item.BagType.White, 300, 150, 75),
            new Item("Dooms Emblem", [], Item.BagType.White, 300, 150, 75),
            new Item("Cavalry Lance", [], Item.BagType.White, 300, 150, 75),
            new Item("Cloak of the Deep", [], Item.BagType.White, 300, 150, 75),
            new Item("Evolutionary Records", [], Item.BagType.White, 300, 150, 75),
            new Item("Pollen Incendiary", [], Item.BagType.White, 300, 150, 75),
            new Item("Bloodbath Blade", [], Item.BagType.White, 300, 150, 75),
            new Item("Runes of Knowledge", [], Item.BagType.White, 300, 150, 75),

            new Item("Barnacle Basher", [], Item.BagType.White, 300, 150, 75), new Item("Barnacle Basher Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Blue Beehemoth Quiver", [], Item.BagType.White, 300, 150, 75), new Item("Blue Beehemoth Quiver Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Red Beehemoth Quiver", [], Item.BagType.White, 300, 150, 75), new Item("Red Beehemoth Quiver Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Yellow Beehemoth Quiver", [], Item.BagType.White, 300, 150, 75), new Item("Yellow Beehemoth Quiver Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Cloak of Bloody Surprises", [], Item.BagType.White, 300, 150, 75), new Item("Cloak of Bloody Surprises Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Crystallised Fangs Venom", ["Pogmur"], Item.BagType.White, 300, 150, 75), new Item("Crystallised Fangs Venom Blueprint", "Exalted Blueprint", ["Pogmur blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Dirk of Cronus", [], Item.BagType.White, 300, 150, 75), new Item("Shiny Dirk of Cronus", [], Item.BagType.White, 900, 450, 225), new Item("Dirk of Cronus Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Hama Yumi", [], Item.BagType.White, 300, 150, 75), new Item("Hama Yumi Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Helm of the Juggernaut", ["Jugg"], Item.BagType.White, 300, 150, 75), new Item("Shiny Helm of the Juggernaut", ["Shiny Jugg"], Item.BagType.White, 900, 450, 225), new Item("Helm of the Juggernaut Blueprint", "Exalted Blueprint", ["Jugg bluprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Kageboshi", [], Item.BagType.White, 300, 150, 75), new Item("Kageboshi Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Kogbold Multitool", [], Item.BagType.White, 300, 150, 75), new Item("Shiny Kogbold Multitool", [], Item.BagType.White, 900, 450, 225), new Item("Kogbold Multitool Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Orb of Conflict", ["Conflict"], Item.BagType.White, 300, 150, 75), new Item("Orb of Conflict Blueprint", "Exalted Blueprint", ["Conflict Blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Quiver of Thunder", ["Qot"], Item.BagType.White, 300, 150, 75), new Item("Quiver of Thunder Blueprint", "Exalted Blueprint", ["Qot blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Seal of Blasphemous Prayer", ["Oreo"], Item.BagType.White, 300, 150, 75), new Item("Shiny Seal of Blasphemous Prayer", ["Shiny Oreo"], Item.BagType.White, 900, 450, 225), new Item("Seal of Blasphemous Prayer Blueprint", "Exalted Blueprint", ["Oreo blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Shield of Ogmur", ["Ogmur"], Item.BagType.White, 300, 150, 75), new Item("Shield of Ogmur Blueprint", "Exalted Blueprint", ["Ogmur Blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Tablet of the Kings Avatar", ["Tablet"], Item.BagType.White, 300, 150, 75), new Item("Tablet of the Kings Avatar Blueprint", "Exalted Blueprint", ["Tablet Blueprint"], Item.BagType.Blue, 200, 100, 50),
            new Item("Token of Warmth", [], Item.BagType.White, 300, 150, 75), new Item("Token of Warmth Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Token of Happiness", [], Item.BagType.White, 300, 150, 75), new Item("Token of Happiness Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Trap of the Vile Spirit", [], Item.BagType.White, 300, 150, 75), new Item("Trap of the Vile Spirit Blueprint", "Exalted Blueprint", [], Item.BagType.Blue, 200, 100, 50),
            new Item("Ray Katana", [], Item.BagType.White, 150, 75, 38), new Item("Shiny Ray Katana", [], Item.BagType.White, 450, 225, 113),

            // T13 weapons
            new Item("Dagger of Sinister Deeds", ["T13 Dagger"], Item.BagType.Red, 35, 0),
            new Item("Bow of Mystical Energy", ["T13 Bow"], Item.BagType.Red, 35, 0),
            new Item("Staff of the Vital Unity", ["T13 Staff"], Item.BagType.Red, 35, 0),
            new Item("Wand of Evocation", ["T13 Wand"], Item.BagType.Red, 35, 0),
            new Item("Sword of Splendor", ["T13 Sword"], Item.BagType.Red, 35, 0),
            new Item("Sadamune", ["T13 Katana"], Item.BagType.Red, 35, 0),
            new Item("Moonstone Blades", ["T13 Dual Daggers"], Item.BagType.Red, 35, 0),
            new Item("Longbow of the Morning Spirit", ["T13 Longbow"], Item.BagType.Red, 35, 0),
            new Item("Spellblade of the Heavens Light", ["T13 Spellblade"], Item.BagType.Red, 35, 0),
            new Item("Morning Star of Conjuration", ["T13 Morningstar"], Item.BagType.Red, 35, 0),
            new Item("Divine Flail", ["T13 Flail"], Item.BagType.Red, 35, 0),
            new Item("Sunset Tachi", ["T13 Tachi"], Item.BagType.Red, 35, 0),

            // T14 Weapons
            new Item("Dagger of Dire Hatred", ["T14 Dagger"], Item.BagType.Red, 50, 0),
            new Item("Bow of Deep Enchantment", ["T14 Bow"], Item.BagType.Red, 50, 0),
            new Item("Staff of the Fundamental Core", ["T14 Staff"], Item.BagType.Red, 50, 0),
            new Item("Wand of Retribution", ["T14 Wand"], Item.BagType.Red, 50, 0),
            new Item("Sword of Majesty", ["T14 Sword"], Item.BagType.Red, 50, 0),
            new Item("Kusanagi", ["T14 Katana"], Item.BagType.Red, 50, 0),
            new Item("Soulforged Blades", ["T14 Dualdaggers"], Item.BagType.Red, 50, 0),
            new Item("Longbow of the Midnight Diamond", ["T14 Longbow"], Item.BagType.Red, 50, 0),
            new Item("Spellblade of the Everlasting Death", ["T14 Spellblade"], Item.BagType.Red, 50, 0),
            new Item("Morning Star of Reckoning", ["T14 Morningstar"], Item.BagType.Red, 50, 0),
            new Item("Gravelords Flail", ["T14 Flail"], Item.BagType.Red, 50, 0),
            new Item("Godslayer Tachi", ["T14 Tachi"], Item.BagType.Red, 50, 0),

            // T14 Armor
            new Item("Wyrmhide Armor", ["T14 Leather"], Item.BagType.Red, 35, 0),
            new Item("Robe of the Star Mother", ["T14 Robe"], Item.BagType.Red, 35, 0),
            new Item("Dominion Armor", ["T14 Heavy"], Item.BagType.Red, 35, 0),

            // T15 Armor
            new Item("Leviathan Armor", ["T15 Leather"], Item.BagType.Red, 50, 0),
            new Item("Robe of the Ancient Intellect", ["T15 Robe"], Item.BagType.Red, 50, 0),
            new Item("Annihilation Armor", ["T15 Heavy"], Item.BagType.Red, 50, 0),

            // T6 Abilities
            new Item("Cloak of Ghostly Concealment", ["T6 Cloak"], Item.BagType.Red, 20, 0),
            new Item("Quiver of Elvish Mastery", ["T6 Quiver"], Item.BagType.Red, 20, 0),
            new Item("Elemental Detonation Spell", ["T6 Spell"], Item.BagType.Red, 20, 0),
            new Item("Tome of Holy Guidance", ["T6 Tome"], Item.BagType.Red, 20, 0),
            new Item("Helm of the Great General", ["T6 Helm"], Item.BagType.Red, 20, 0),
            new Item("Colossus Shield", ["T6 Shield"], Item.BagType.Red, 20, 0),
            new Item("Seal of the Blessed Champion", ["T6 Seal"], Item.BagType.Red, 20, 0),
            new Item("Baneserpent Poison", ["T6 Poison"], Item.BagType.Red, 20, 0),
            new Item("Bloodsucker Skull", ["T6 Skull"], Item.BagType.Red, 20, 0),
            new Item("Giantcatcher Trap", ["T6 Trap"], Item.BagType.Red, 20, 0),
            new Item("Planefetter Orb", ["T6 Orb"], Item.BagType.Red, 20, 0),
            new Item("Prism of Apparitions", ["T6 Prism"], Item.BagType.Red, 20, 0),
            new Item("Scepter of Storms", ["T6 Scepter"], Item.BagType.Red, 20, 0),
            new Item("Doom Circle", ["T6 Star"], Item.BagType.Red, 20, 0),
            new Item("Royal Wakizashi", ["T6 Waki"], Item.BagType.Red, 20, 0),
            new Item("Skyward Lute", ["T6 Lute"], Item.BagType.Red, 20, 0),
            new Item("Sovereign Mace", ["T6 Mace"], Item.BagType.Red, 20, 0),
            new Item("Great Shinobi Sheath", ["T6 Sheath"], Item.BagType.Red, 20, 0),

            // T7 Abilities
            new Item("Cloak of Nightmares", ["T7 Cloak"], Item.BagType.Red, 50, 0),
            new Item("Quiver of the Autumn King", ["T7 Quiver"], Item.BagType.Red, 50, 0),
            new Item("Burning Retribution Spell", ["T7 Spell"], Item.BagType.Red, 50, 0),
            new Item("Tome of Hallowed Language", ["T7 Tome"], Item.BagType.Red, 50, 0),
            new Item("Helm of the Tribune", ["T7 Helm"], Item.BagType.Red, 50, 0),
            new Item("Shield of Orcish Regalia", ["T7 Shield"], Item.BagType.Red, 50, 0),
            new Item("Seal of Invocation", ["T7 Seal"], Item.BagType.Red, 50, 0),
            new Item("Necrofish Poison", ["T7 Poison"], Item.BagType.Red, 50, 0),
            new Item("Mindwaster Skull", ["T7 Skull"], Item.BagType.Red, 50, 0),
            new Item("Depthchaser Trap", ["T7 Trap"], Item.BagType.Red, 50, 0),
            new Item("Dimensiongate Orb", ["T7 Orb"], Item.BagType.Red, 50, 0),
            new Item("Prism of Reveries", ["T7 Prism"], Item.BagType.Red, 50, 0),
            new Item("Scepter of the Firmament", ["T7 Scepter"], Item.BagType.Red, 50, 0),
            new Item("Dynastic Star", ["T7 Star"], Item.BagType.Red, 50, 0),
            new Item("Virtuous Wakizashi", ["T7 Waki"], Item.BagType.Red, 50, 0),
            new Item("Nebular Lute", ["T7 Lute"], Item.BagType.Red, 50, 0),
            new Item("Grandmaster Mace", ["T7 Mace"], Item.BagType.Red, 50, 0),
            new Item("Sonic Wave Sheath", ["T7 Sheath"], Item.BagType.Red, 50, 0),

            // T7 Rings
            new Item("Ring of Transcendent Health", ["T7 Health", "T7 hp"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Magic", ["T7 Mana", "T7 mp"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Attack", ["T7 Attack", "T7 atk"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Defense", ["T7 Defense", "T7 def"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Speed", ["T7 Speed", "T7 spd"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Dexterity", ["T7 Dexterity", "T7 dex"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Vitality", ["T7 Vitality", "T7 vit"], Item.BagType.Red, 50, 0),
            new Item("Ring of Transcendent Wisdom", ["T7 Wisdom", "T7 wis"], Item.BagType.Red, 50, 0),
        ];

        public static Set[] sets = [
            // Ut's
            new Set("Crystal Necromancer", ["Staff of the Crystal Serpent", "Cracked Crystal Skull", "Robe of the Tlatoani", "Crystal Bone Ring"], 80, 20),
            new Set("Spirit Mystic", ["Spirit Staff", "Enchantment Orb", "Woodland Robe", "Fairy Ring"], 180, 45),
            new Set("Mad Scientist Sorcerer", ["Conducting Wand", "Scepter of Fulmination", "Robe of the Mad Scientist", "Experimental Ring"], 225, 57),
            new Set("Coral Huntress", ["Coral Bow", "Coral Venom Trap", "Coral Silk Armor", "Coral Ring"], 280, 70),
            new Set("Purified Priest", ["St Abrahams Wand", "Tome of Purification", "Chasuble of Holy Light", "Ring of Divine Faith"], 150, 38),
            new Set("Ghostly Trickster", ["Spirit Dagger", "Ghostly Prism", "Spectral Cloth Armor", "Captains Ring"], 280, 70),
            new Set("Esben Necromancer", ["Staff of Esben", "Skullish Remains of Esben", "Esbens Shaman Attire", "Esbens Wedding Ring"], 360, 90),
            new Set("Cultist Necromancer", ["Staff of Unholy Sacrifice", "Skull of Corrupted Souls", "Ritual Robe", "Bloodshed Ring"], 480, 120),
            new Set("Marble Paladin", ["Sword of the Colossus", "Marble Seal", "Breastplate of New Life", "Magical Lodestone"], 480, 120),
            new Set("Void Archer", ["Bow of the Void", "Quiver of the Shadows", "Armor of Nil", "Sourcestone"], 480, 120),
            new Set("Chancellor Wizard", ["Superior", "Genesis Spell", "Diplomatic Robe", "Chancellors Cranium"], 480, 120),
            new Set("Treasurer Trickster", ["Avarice", "Gamblers Fate", "Turncoat Cape", "Collectors Monocle"], 480, 120),
            new Set("Archbishop Priest", ["Lumiaire", "Chaotic Scripture", "Vesture of Duality", "Divine Coronation"], 480, 120),
            new Set("Chief Ninja", ["Enforcer", "Ballistic Star", "Centaurs Shielding", "Battalion Banner"], 480, 120),
            new Set("Exalted Knight", ["Divinity", "Oryxs Escutcheon", "Gladiator Guard", "Exalted Gods Horn"], 480, 120),

            // St's
            new Set("Vampire Rogue", ["Soulcursed Scythe", "Vampiric Cape", "Hallowed Hide", "Ruthvens Rosary"], 240, 60),
            new Set("Skuld 2 The ReGhostening", ["Etherite Dagger", "Ghastly Drape", "Mantle of Skuld", "Spectral Ring of Horrors"], 240, 60),
            new Set("Treasure Hunter Archer", ["Resplendent Bow", "Embellished Quiver", "Ornate Armor", "Aquamarine Amulet"], 240, 60),
            new Set("Phantom Archer", ["Deathless Crossbow", "Quiver of Shrieking Specters", "Wraiths Brigandine", "Revenant Ring"], 300, 75),
            new Set("Slurp Scion Wizard", ["Tideturner Trident", "Slurpian Sea Scroll", "Oceanic Apparel", "Imperial Keepsake"], 300, 75),
            new Set("Twilight Archmage", ["Corruption Tether", "Ancient Eminence", "Twilight Shroud", "Defiled Equilibrium"], 440, 110),
            new Set("Priest of Geb", ["Wand of Geb", "Book of Geb", "Shendyt of Geb", "Gebs Ring of Wisdom"], 360, 90),
            new Set("Mad Gods Messenger", ["Theurgy Wand", "Ceremonial Merlot", "Anointed Robe", "Ring of Pagan Favor"], 240, 60),
            new Set("Pirate King Warrior", ["Swashbucklers Sickle", "Tricorne of the High Seas", "Naval Uniform", "First Mates Hook"], 360, 90),
            new Set("Dragon Tamer", ["Indomptable", "Helm of Draconic Dominance", "Zaarvoxs Heart", "Amulet of Drakefyre"], 360, 90),
            new Set("Nordic Knight", ["Dalvars Battle Axe", "Sunken Buckler", "Chainmail Body Armor", "Gjallarhorn"], 360, 90),
            new Set("Oryxs Battle Attires", ["Oryxs Greatsword", "Champions Bastion", "Mercys Bane", "Bloodstone Ring"], 360, 90),
            new Set("Corrupted Paladin", ["Fallen Ones Blade", "Abyssal Insignia", "Vortex Plating", "Eye of the Void"], 440, 110),
            new Set("Swoll Paladin", ["Pixie Enchanted Sword", "Seal of the Enchanted Forest", "Fairy Plate", "Ring of Pure Wishes"], 360, 90),
            new Set("Acidified Assassin", ["Toxin Tooth", "Virulent Venom", "Acidic Armor", "Pernicious Peridot"], 360, 90),
            new Set("Flesh Collector", ["Symbiotic Ripper", "Parasitic Concoction", "Rags of the Host", "Hivemind Circlet"], 360, 90),
            new Set("Hollow King Necromancer", ["Edictum Praetoris", "Memento Mori", "Toga Picta", "Interregnum"], 240, 60),
            new Set("Cuboid Necromancer", ["Squaroid Staff", "Cubic Frame", "Polygonal Garbs", "Cuband"], 360, 90),
            new Set("Horticultural Huntress", ["Bergenia Bow", "Lifebringing Lotus", "Hollyhock Hide", "Chrysanthemum Corsage"], 360, 90),
            new Set("Swarming Huntress", ["Nectar Crossfire", "Honeytomb Snare", "Apiary Armor", "Honey Circlet"], 440, 110),
            new Set("Magmatic Mystic", ["Staff of Eruption", "Scorchium Stone", "Molten Mantle", "Ring of the Inferno"], 240, 60),
            new Set("Phylactery Mystic", ["The Phylactery", "Soul of the Bearer", "Soulless Robe", "Ring of the Covetous Heart"], 240, 60),
            new Set("Daeva Trickster", ["Archangels Judgement", "Daevite Progenitor", "Seraphims Guard", "Flames of Genesis"], 440, 110),
            new Set("Lost Golem", ["Carved Golem Remains", "Brain of the Golem", "Golem Garments", "Rusty Cuffs"], 440, 110),
            new Set("Court Magician Sorcerer", ["Magic Wand", "Lightshow Scepter", "Magicians Robe", "Performers Hat"], 360, 90),
            new Set("Horrific Sorcerer", ["Abominations Wrath", "Grotesque Scepter", "Garment of the Beast", "Horrific Claws"], 360, 90),
            new Set("Crystal Kunoichi", ["Quartz Cutter", "Crystalline Kunai", "Luminous Armor", "Radiant Heart"], 440, 110),
            new Set("Raijin Disciple", ["Reikoku", "Daybreak Chakram", "Hirejou Tenne", "Heavenly Magatama"], 360, 90),
            new Set("Daring Discoverer Samurai", ["Kiritsukeru", "Watarimono", "Reinforced Root Armor", "Travelers Trinket"], 240, 60),
            new Set("Akuma Slayer", ["Kazekiri", "Ryus Blade", "Kamishimo", "Akumas Tear"], 360, 90),
            new Set("Storm Caller Bard", ["Hailstorm", "Thundering Chorus", "Wind Dancer Robe", "Augur of the Tempest"], 360, 90),
            new Set("Angelic Bard", ["Harmonious Harp", "Angels Fanfare", "Wings of Sanctity", "Heavenly Halo"], 440, 110),
            new Set("Earthen Bulwark Summoner", ["Earthen Ward", "Stonemould Mace", "Rocky Robe", "Steadfast Glyph"], 360, 90),
            new Set("Scientific Summoner", ["CLAW", "BOOM", "ARMOR", "CONTROLLER"], 360, 90),
            new Set("Fiery Kensei", ["Fiery Katana", "Pyro Sheath", "Flame Guard", "Firelight Necklace"], 360, 90),
            new Set("Tidal Wave Kensei", ["Saif of the Deep", "Loch Sheath", "Barrier Reef", "Alexanders Band"], 360, 90),

            // Other
            new Set("T7 Ring Collection", ["Ring of Transcendent Health", "Ring of Transcendent Magic", "Ring of Transcendent Attack", "Ring of Transcendent Defense", "Ring of Transcendent Speed", "Ring of Transcendent Dexterity", "Ring of Transcendent Vitality", "Ring of Transcendent Wisdom"], 400, 0)
        ];

    }
}
